Planning-Inspectorate/appeals-prototype

app/views/appellant-submission/v11/before-you-start/check-answers.html

BYS = Before You Start
CYA = Check Your Answers

Content fix to deadline on BYS CYA

---

app/routes/inspector/v5.js
app/views/inspector/v5/book-visit/check-confirm.html
app/views/inspector/v5/book-visit/date-time.html

Still requires content updates

Updated flow for booking site visits

---

app/assets/sass/application.scss
app/assets/sass/pins/tables.scss
app/views/index.html
app/views/interested-party/v1/appeal-comment-email.html
app/views/interested-party/v1/appeal-comment-name.html
app/views/interested-party/v1/appeal-details.html
app/views/interested-party/v1/appeal-search-no-results.html
app/views/interested-party/v1/appeal-search-results.html
app/views/interested-party/v1/appeal-search.html
app/views/interested-party/v1/check-answers.html
app/views/interested-party/v1/comment-received.html
app/views/interested-party/v1/comment-upload.html
app/views/interested-party/v1/guidance.html

This PR has Wesleys fix with added accordion row to show the links to the Interested Party can comment on an appeal links to JIRA and screens.

Interested party links back in index

---

app/views/index.html
app/views/interested-party/v1/appeal-details.html

Updates to appeal screen based on status of appeal.

Interested parties can comment

---

app/views/index.html
app/views/interested-party/v1/appeal-comment-email.html
app/views/interested-party/v1/appeal-comment-name.html
app/views/interested-party/v1/appeal-details.html
app/views/interested-party/v1/comment-upload.html
app/views/interested-party/v1/guidance.html
app/views/interested-party/v1/householder-appeal-first-notice-letter.html

Comment on appeal content and design updates

---

app/views/index.html

Quick update to the index status for this work.

Interested parties can comment status update

---

app/views/index.html

Index update for interested parties

---

app/views/interested-party/v1/appeal-details.html

Small content update to help make the appeal location meta data match up.

Small address change for research to make the demo make more sense

---

app/views/interested-party/v1/comment-upload.html
app/views/interested-party/v1/guidance.html
app/views/interested-party/v1/householder-appeal-first-notice-letter.html
app/views/interested-party/v1/householder-appeal-first-notice.html

Making the addresses match in the notification letter.

Matching addresses in the letter

---

app/views/index.html
app/views/interested-party/v2/appeal-comment-email.html
app/views/interested-party/v2/appeal-comment-name.html
app/views/interested-party/v2/appeal-details.html
app/views/interested-party/v2/appeal-search-no-results.html
app/views/interested-party/v2/appeal-search-results.html
app/views/interested-party/v2/appeal-search.html
app/views/interested-party/v2/appeal-stage.html
app/views/interested-party/v2/check-answers.html
app/views/interested-party/v2/comment-received.html
app/views/interested-party/v2/comment-upload.html
app/views/interested-party/v2/full-planning-appeal-first-notice.html
app/views/interested-party/v2/guidance.html
app/views/interested-party/v2/householder-appeal-first-notice-letter.html
app/views/interested-party/v2/householder-appeal-first-notice.html

Setting up version 2 of the _interested parties_ work for the next sprint.

Interested parties, version 2 for sprint Barbados

---

app/views/index.html
app/views/interested-party/v2/appeal-details.html
app/views/interested-party/v2/appeal-search-address.html
app/views/interested-party/v2/appeal-search-reference.html
app/views/interested-party/v2/appeal-select-address.html

Update to the appeal search to include address search.
Change in order on the appeal detail screen, to improve accessibility.

Interested parties, address search, update to appeal details screen

---

app/assets/sass/pins/tables.scss
app/views/index.html
app/views/interested-party/v1/appeal-details.html
app/views/interested-party/v2/appeal-details.html
app/views/interested-party/v2/appeal-search-address.html
app/views/interested-party/v2/appeal-search-reference.html
app/views/interested-party/v2/appeal-select-appeal.html
app/views/interested-party/v2/check-answers.html
app/views/interested-party/v2/guidance.html

Updates to the journey, content and dynamic values updates.

Interested parties can comment updates

---

app/views/interested-party/v2/comment-received.html

Dynamic appeal reference on the confirmation screen, based on appeal code used / selected search results.

'appealCode' on the Comment received screen

---

app/views/index.html
app/views/interested-party/v2/appeal-details.html
app/views/interested-party/v2/appeal-search-no-results.html
app/views/interested-party/v2/appeal-select-appeal.html

Updates to interested parties journey, mostly to search results.

Updates to search results for interested parties

---

app/views/index.html
app/views/interested-party/v2/appeal-details.html
app/views/interested-party/v2/appeal-search-address.html
app/views/interested-party/v2/appeal-select-appeal.html
app/views/interested-party/v2/check-answers.html
app/views/interested-party/v2/closed-appeals.html
app/views/interested-party/v2/comment-received.html
app/views/interested-party/v2/guidance.html

Content updates in preparation of research tomorrow.

Interested parties content updates

---

app/routes.js
app/routes/interested-party/upload-comments.js
app/views/index.html
app/views/interested-party/v3/appeal-comment-email.html
app/views/interested-party/v3/appeal-comment-name.html
app/views/interested-party/v3/appeal-details.html
app/views/interested-party/v3/appeal-search-no-results.html
app/views/interested-party/v3/appeal-search-reference.html
app/views/interested-party/v3/appeal-stage.html
app/views/interested-party/v3/check-answers.html
app/views/interested-party/v3/comment-received.html
app/views/interested-party/v3/comment-upload-list.html
app/views/interested-party/v3/comment-upload.html
app/views/interested-party/v3/comments-received-confirmation.html
app/views/interested-party/v3/guidance.html
app/views/interested-party/v3/householder-appeal-first-notice-letter.html
app/views/interested-party/v3/select-appeal.html

Version 3 updates and removals. Content changes.
(Upload screen routing not working)

Interested parties v3 updates

---

app/routes/interested-party/upload-comments.js
app/views/interested-party/v3/comment-upload-list.html
app/views/interested-party/v3/comment-upload.html

Fixes to the multi-file upload (updating the branch, merging to get everything inline).

Westley’s fixes to upload lists

---

app/views/final-comments/v1/_lpd-details.html
app/views/lpa-questionnaire/fullv2/_appeal-details.html
app/views/statement-of-case/v1/_lpd-details.html

Addition of full appeal reference to sidebar in LPD Final comments and Statement of case

AS-4366 AS-4394 AS-4396

---

app/views/interested-party/v3/check-answers.html
app/views/interested-party/v3/comment-upload-list.html
app/views/interested-party/v3/comment-upload.html

Making sure that screens with upload comments data show multiple files where they exist.

Multi-upload information on relevant screens

---

app/views/interested-party/v3/appeal-details.html

Appeal details, decision types shown using the variable: decision
So:
status = completed
decision = allowed, disallowed, split or invalid

Appeal details, decision types

---

app/views/index.html
app/views/interested-party/v3/appeal-decision.html
app/views/interested-party/v3/comment-received.html
app/views/interested-party/v3/comments-received-confirmation.html
app/views/local-planning-department/v1/householder-appeal-first-notice-template.html

Local planning department notice template and small content updattes to IP journey.

Content tweaks, addition of local planning IP notice template

---

app/views/local-planning-department/v1/householder-appeal-first-notice-template.html

Double bracketting and addition of blank PINs email address.

Small change to interested party LPD notice template

---

app/filters.js
app/views/final-comments/v1/lpd/check-your-answers.html
app/views/final-comments/v1/lpd/confirmation.html
app/views/index.html
app/views/lpd-comms/v1/comments-submitted.html
app/views/lpd-comms/v1/inbox-comments-submitted.html
app/views/lpd-comms/v1/inbox-started-refusal.html
app/views/lpd-comms/v1/inbox-statement-submitted.html
app/views/lpd-comms/v1/started-refusal.html
app/views/lpd-comms/v1/statement-submitted.html
app/views/statement-of-case/v1/confirmation.html

LPD comms ready for UR

---

app/routes/interested-party/upload-comments.js
app/views/interested-party/v3/comment-upload-list.html
app/views/interested-party/v3/comment-upload.html

'File name' and fix to the upload routing.

Fix to upload routing

---

app/views/index.html
app/views/interested-party/v3/appeal-details.html

Small updates to index, hiding the decision link from the appeal details screen.

Small updates, hiding decision link on appeals

---

app/views/index.html
app/views/interested-party/v4/appeal-comment-email.html
app/views/interested-party/v4/appeal-comment-name.html
app/views/interested-party/v4/appeal-decision.html
app/views/interested-party/v4/appeal-details.html
app/views/interested-party/v4/appeal-search-no-results.html
app/views/interested-party/v4/appeal-search-reference.html
app/views/interested-party/v4/appeal-stage.html
app/views/interested-party/v4/check-answers.html
app/views/interested-party/v4/comment-delete.html
app/views/interested-party/v4/comment-received.html
app/views/interested-party/v4/comment-upload-list.html
app/views/interested-party/v4/comment-upload.html
app/views/interested-party/v4/comments-received-confirmation.html
app/views/interested-party/v4/guidance.html
app/views/interested-party/v4/householder-appeal-first-notice-letter.html
app/views/interested-party/v4/select-appeal.html

Version 4 folder for the interested parties work and added placeholder accordion for the new sprint.

Interested parties index update for new sprint

---

app/views/index.html
app/views/interested-party/v4/appeal-details.html
app/views/interested-party/v4/closed-appeals.html
app/views/interested-party/v4/guidance.html
app/views/interested-party/v4/open-appeals.html

Iteration for testing for people who want to find out about appeals that may affect them. Comment on an appeal is included here. Version 4 for team review.

Version 4 of the interested parties service

---

app/routes/interested-party/upload-comments.js
app/views/index.html
app/views/interested-party/v4/appeal-details.html
app/views/interested-party/v4/appeal-number.html
app/views/interested-party/v4/appeal-search-postcode.html
app/views/interested-party/v4/appeal-search-reference.html
app/views/interested-party/v4/closed-appeals.html
app/views/interested-party/v4/guidance.html
app/views/interested-party/v4/open-appeals.html

Updates for interested parties research.

Interested party

---

app/views/interested-party/v4/guidance.html

Small update to guidance for interested parties.

Interested parties guidance update

---

app/views/interested-party/v4/appeal-decision.html

Addition of letter part of the appeal decision.

Appeal decision additions

---

app/views/interested-party/v4/appeal-details.html

Removing link to decision on open appeal details

---

app/views/index.html

Updated index to show results.

Congo updates to index

---

app/views/interested-party/v4/closed-appeals.html
app/views/interested-party/v4/open-appeals.html

Content updates for interested parties.

Appeals content updates

---

app/routes.js
app/routes/save-progress/v1.js
app/views/layouts/save-progress/v1.html
app/views/save-progress/v1/appeal-saved-email.html
app/views/save-progress/v1/appeal-saved.html
app/views/save-progress/v1/check-answers.html
app/views/save-progress/v1/confirm-email.html
app/views/save-progress/v1/confirmation-email.html
app/views/save-progress/v1/contact-details/applicant-name.html
app/views/save-progress/v1/contact-details/how-to-answer.html
app/views/save-progress/v1/contact-details/who-are-you.html
app/views/save-progress/v1/contact-details/your-details.html
app/views/save-progress/v1/email-confirmed.html
app/views/save-progress/v1/email-inbox.html
app/views/save-progress/v1/task-list.html
app/views/save-progress/v1/what-is-your-email.html

Dropping the basic set of screens in for our 1st set of plans for Save progress

Rough additions for save progress

---

app/views/index.html
app/views/save-progress/v1/appeal-saved.html
app/views/save-progress/v1/check-answers.html
app/views/save-progress/v1/confirm-email-resent.html
app/views/save-progress/v1/confirm-email.html
app/views/save-progress/v1/contact-details/your-details.html
app/views/save-progress/v1/expired-link.html
app/views/save-progress/v1/incomplete-appeals.html
app/views/save-progress/v1/input-magic-link-email.html
app/views/save-progress/v1/magic-link-email-sent.html
app/views/save-progress/v1/magic-link-email.html
app/views/save-progress/v1/return-email.html
app/views/save-progress/v1/task-list.html
app/views/save-progress/v1/what-is-your-application-number.html

Content and screens for the Save progress plans

Updates to save progress

---

app/routes.js
app/routes/appellant-submission/v13.js
app/routes/save-progress/v1/v1.js
app/views/appellant-submission/v13/full/contact-details/who-are-you.html
app/views/save-progress/v1/appeal-saved.html
app/views/save-progress/v1/check-answers.html
app/views/save-progress/v1/confirm-email-resent.html
app/views/save-progress/v1/incomplete-appeals.html
app/views/save-progress/v1/task-list.html
app/views/save-progress/v1/what-do-you-want-to-do.html

Updates to screens and routing for appeal journey start

Save progress updates, logic fixed

---

app/views/layouts/save-progress/v2.html
app/views/save-progress/v2/appeal-saved.html
app/views/save-progress/v2/before-you-continue.html
app/views/save-progress/v2/email-confirmed.html
app/views/save-progress/v2/input-magic-link-email.html
app/views/save-progress/v2/task-list.html

Content updates and alternate journey

Save progress version 2 updates

---

app/routes/save-progress/v2/v2.js
app/views/index.html
app/views/save-progress/v2/appeal-saved.html
app/views/save-progress/v2/before-you-continue.html
app/views/save-progress/v2/confirm-email.html
app/views/save-progress/v2/confirmation-email.html
app/views/save-progress/v2/contact-details/who-are-you.html
app/views/save-progress/v2/contact-details/your-details.html
app/views/save-progress/v2/email-confirmed.html
app/views/save-progress/v2/incomplete-appeals.html
app/views/save-progress/v2/return-email.html
app/views/save-progress/v2/what-is-your-email.html

Save progress content updates.

Save progress updates

---

app/views/index.html
app/views/save-progress/v2/appeal-saved-email.html
app/views/save-progress/v2/confirmation-email.html
app/views/save-progress/v2/magic-link-email.html
app/views/save-progress/v2/return-email.html
app/views/save-progress/v2/v13.js

Content and format updates to save progress plans.

Content tweaks to v2 of save progress

---

app/views/index.html
app/views/save-progress/v2/appeal-saved.html
app/views/save-progress/v2/before-you-continue.html
app/views/save-progress/v2/confirm-email-resent.html
app/views/save-progress/v2/confirm-email.html
app/views/save-progress/v2/contact-details/your-details.html
app/views/save-progress/v2/inbox-1.html
app/views/save-progress/v2/inbox-2.html
app/views/save-progress/v2/inbox-3.html
app/views/save-progress/v2/magic-link-email-sent.html
app/views/save-progress/v2/magic-link-email.html
app/views/save-progress/v2/return-email.html
app/views/save-progress/v2/task-list.html

Updates for save progress, addition of an email inbox UI.

Save progress

---

app/views/save-progress/v2/magic-link-email-sent.html
app/views/save-progress/v2/magic-link-email.html
app/views/save-progress/v2/return-email.html

Content tweaks for Save progress

Small updates to save progress journey

---

app/views/save-progress/v2/confirm-email-resent.html
app/views/save-progress/v2/confirm-email.html

Removing the telephone link from the 2 other instances.

Removing the telephone number link

---

app/views/save-progress/v2/check-answers.html
app/views/save-progress/v2/return-email.html

Small updates to dynamic content

Small data fixes to save progress

---

app/views/index.html

Index status update for Save progress work.

Index update 'Ready for UR'

---

app/views/save-progress/v2/inbox-1.html
app/views/save-progress/v2/return-email.html

Final content changes done in Sprint 12

Last changes for v2 of Save progress

---

app/views/index.html
app/views/save-progress/v3/appeal-closed.html
app/views/save-progress/v3/appeal-saved-email.html
app/views/save-progress/v3/appeal-saved.html
app/views/save-progress/v3/before-you-continue.html
app/views/save-progress/v3/check-answers.html
app/views/save-progress/v3/confirm-email-resent.html
app/views/save-progress/v3/confirm-email.html
app/views/save-progress/v3/confirmation-email.html
app/views/save-progress/v3/contact-details/who-are-you.html
app/views/save-progress/v3/contact-details/your-details.html
app/views/save-progress/v3/email-confirmed.html
app/views/save-progress/v3/email-inbox.html
app/views/save-progress/v3/expired-link.html
app/views/save-progress/v3/inbox-1.html
app/views/save-progress/v3/inbox-2.html
app/views/save-progress/v3/inbox-3.html
app/views/save-progress/v3/incomplete-appeals.html
app/views/save-progress/v3/input-magic-link-email.html
app/views/save-progress/v3/magic-link-email-sent.html
app/views/save-progress/v3/magic-link-email.html
app/views/save-progress/v3/return-email.html
app/views/save-progress/v3/service-start.html
app/views/save-progress/v3/task-list.html
app/views/save-progress/v3/v13.js
app/views/save-progress/v3/what-is-your-application-number.html
app/views/save-progress/v3/what-is-your-email.html

Updated content for user research in sprint 13.

Content iteration for save progress

---

app/views/index.html

Adding research notes to Save progress links

Index update

---

app/views/guidance/full/v2/before-you-appeal.html
app/views/guidance/full/v2/overview.html

Small updates for public guidance

Small content updates for public guidance

---

app/views/guidance/full/v2/comment-on-planning-appeal.html

Making some h3s to h2s on the new page.

Heading size fixes

---

app/views/guidance/full/v2/overview.html
app/views/index.html

Added link for public guidance screens.

Public guidance, added link for listed buildings

---

app/views/guidance/full/v2/before-you-appeal.html
app/views/guidance/full/v2/claim-costs-for-your-appeal.html
app/views/guidance/full/v2/comment-on-planning-appeal.html
app/views/guidance/full/v2/stages-of-an-appeal.html
app/views/guidance/full/v2/submit-an-appeal.html
app/views/guidance/full/v2/when-you-can-appeal.html
app/views/guidance/full/v2/your-appeal-decision.html
app/views/guidance/full/v2/your-appeal-statement.html
app/views/includes/contact-information
app/views/includes/having-problems-contact-us

New page structure, also start page with green start button.

Public guidance content updates + start page

---

app/views/before-you-start/v10/enforcement-notice.html
app/views/guidance/full/v2/before-you-appeal.html
app/views/guidance/full/v2/claim-costs-for-your-appeal.html
app/views/guidance/full/v2/comment-on-planning-appeal.html
app/views/guidance/full/v2/overview.html
app/views/guidance/full/v2/stages-of-an-appeal.html
app/views/guidance/full/v2/submit-an-appeal.html
app/views/guidance/full/v2/when-you-can-appeal.html
app/views/guidance/full/v2/your-appeal-decision.html
app/views/guidance/full/v2/your-appeal-statement.html
app/views/index.html

Updates to guidance screens.
Hack to link Before you start to Save and return prototypes.

Changes to guidance screen order + hack for BYS > SAR

---

app/views/footer/index.html
app/views/guidance/full/v2/your-appeal-statement.html
app/views/includes/sensitive-info-list.html
app/views/interested-party/v4/guidance.html

Update to content for sensitive information in the ‘Your appeal statement’ public guidance and the _Interested party_ guidance.

Sensitive info update

---

app/assets/sass/application.scss
app/assets/sass/pins/prototype-only.scss
app/routes.js
app/routes/save-progress/v3/v3.js
app/views/index.html
app/views/layouts/save-progress/v2-no-back.html
app/views/save-progress/v3/appeal-saved.html
app/views/save-progress/v3/before-you-continue.html
app/views/save-progress/v3/confirm-email-resent.html
app/views/save-progress/v3/email-confirmed.html
app/views/save-progress/v3/expired-link.html
app/views/save-progress/v3/incomplete-appeals.html
app/views/save-progress/v3/input-magic-link-email.html
app/views/save-progress/v3/magic-link-email-resent.html
app/views/save-progress/v3/magic-link-email.html
app/views/save-progress/v3/task-list.html
app/views/save-progress/v3/what-is-your-application-number.html

I used the wrong branch.
Here are logic updates in the Save and return work to fix some routing things and remove unneccessary back buttons.

Wrong branch, save progress logic updates

---

app/views/index.html
app/views/layouts/save-progress/v3-no-back.html
app/views/layouts/save-progress/v3.html
app/views/save-progress/v3/appeal-submitted.html
app/views/save-progress/v3/check-your-answers.html
app/views/save-progress/v3/code-expired.html
app/views/save-progress/v3/email-with-code.html
app/views/save-progress/v3/input-code.html
app/views/save-progress/v3/return-email.html
app/views/save-progress/v3/task-list.html
app/views/save-progress/v3/you-cannot-appeal.html

Content updates for the code version of _Save and return_

Save progress 'code' updates

---

app/views/save-progress/v3/input-code.html
app/views/save-progress/v3/request-code.html

Addition of the loop to request a new code if you did not receive one.
+ errant full stop fix

Request a new code loop

---

app/routes/before-you-start/v11.js
app/views/enforcement/v1/appeal-site/health-and-safety-issues.html
app/views/enforcement/v1/appeal-site/site-interest.html
app/views/enforcement/v1/appeal-site/site-visibility.html
app/views/enforcement/v1/grounds/groundA-file.html
app/views/enforcement/v1/grounds/groundA-text.html
app/views/enforcement/v1/grounds/groundB-file.html
app/views/enforcement/v1/grounds/groundB-text.html
app/views/enforcement/v1/grounds/groundC-text.html
app/views/enforcement/v1/grounds/groundD-text.html
app/views/enforcement/v1/grounds/groundE-text.html
app/views/enforcement/v1/grounds/groundF-text.html
app/views/enforcement/v1/grounds/groundG-text.html
app/views/enforcement/v1/grounds/grounds.html

Grounds of appeal and reasons logic

More enforcement screens

---

app/routes.js
app/routes/before-you-start/v11.js
app/routes/enforcement/v1.js
app/views/enforcement/v1/check-your-answers.html
app/views/enforcement/v1/confirmation.html
app/views/enforcement/v1/declaration.html
app/views/enforcement/v1/grounds/late-application.html
app/views/enforcement/v1/grounds/procedure.html
app/views/enforcement/v1/upload/enforcement-notice.html
app/views/enforcement/v1/upload/planning-obligation.html
app/views/enforcement/v1/upload/plans-or-drawings.html

Happy path screens to confirmation

Enforcement additions

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/appeal-site/other-appeals.html
app/views/enforcement/v1/appeal-site/owner-consent.html
app/views/enforcement/v1/appeal-site/site-occupation.html
app/views/enforcement/v1/appeal-site/your-interest.html
app/views/enforcement/v1/contact-details/who-was-served.html
app/views/enforcement/v1/upload/obligation-draft.html
app/views/enforcement/v1/upload/obligation-not-started.html
app/views/enforcement/v1/upload/obligation-ready.html
app/views/enforcement/v1/upload/planning-obligation-status.html

Other pathways for the enforcement journey.

Additions to enforcement screens

---

app/routes/before-you-start/v11.js
app/routes/enforcement/v1.js
app/views/before-you-start/v11/appeal-intent.html
app/views/before-you-start/v11/check-answers.html
app/views/before-you-start/v11/enforcement-effective-date.html
app/views/before-you-start/v11/enforcement-issue-date.html
app/views/before-you-start/v11/index.html
app/views/before-you-start/v11/shutter/listed-building-enforcement-notice.html
app/views/before-you-start/v11/shutter/out-of-time-enforcement.html
app/views/enforcement/v1/before-you-continue.html
app/views/enforcement/v1/check-your-answers.html
app/views/enforcement/v1/confirmation.html
app/views/enforcement/v1/contact-details/who-was-served.html
app/views/enforcement/v1/declaration.html
app/views/enforcement/v1/grounds/groundG-text.html
app/views/enforcement/v1/upload/enforcement-notice.html
app/views/enforcement/v1/upload/obligation-draft.html
app/views/enforcement/v1/upload/obligation-not-started.html
app/views/enforcement/v1/upload/obligation-ready.html
app/views/index.html

Wrapping up logic and content tweaks for enforcement journey + index links to journeys and design boards.

Enforcement

---

app/views/before-you-start/v11/index.html

Tiny fix to BYS link

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/additional-people/add-person.html
app/views/enforcement/v1/additional-people/added-people.html
app/views/enforcement/v1/additional-people/additional-people.html
app/views/enforcement/v1/appeal-site/grid-address.html
app/views/enforcement/v1/appeal-site/health-and-safety-issues.html
app/views/enforcement/v1/appeal-site/other-appeals.html
app/views/enforcement/v1/appeal-site/postcode-address.html
app/views/enforcement/v1/appeal-site/site-interest.html
app/views/enforcement/v1/appeal-site/site-visibility.html
app/views/enforcement/v1/appeal-site/your-interest.html
app/views/enforcement/v1/check-your-answers.html
app/views/enforcement/v1/contact-details/contact-details.html
app/views/enforcement/v1/contact-details/who-are-you.html
app/views/enforcement/v1/contact-details/who-was-served.html
app/views/enforcement/v1/grounds/application-decision.html
app/views/enforcement/v1/grounds/late-application.html

Mostly check your answer additions

---

app/routes/enforcement/v1.js

Routing fixed for the late application question, it will ask the decision question if an applicaiton was sent.

Fix to late application decision routing

---

app/routes/before-you-start/v11.js
app/views/enforcement/v1/appeal-site/owner-consent.html
app/views/enforcement/v1/appeal-site/site-occupation.html
app/views/enforcement/v1/task-list.html

Small fixes for enforcement including removing errant hints.

Small changes to enforcement journey

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/appeal-site/other-appeals.html
app/views/enforcement/v1/check-your-answers.html
app/views/enforcement/v1/grounds/application.html
app/views/enforcement/v1/grounds/groundA-file.html
app/views/enforcement/v1/grounds/groundA-text.html
app/views/enforcement/v1/grounds/groundB-file.html
app/views/enforcement/v1/grounds/groundB-text.html
app/views/enforcement/v1/grounds/groundC-text.html
app/views/enforcement/v1/grounds/groundD-text.html
app/views/enforcement/v1/grounds/groundE-text.html
app/views/enforcement/v1/grounds/groundF-text.html
app/views/enforcement/v1/grounds/groundG-text.html

Fixes to Grounds status issues

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/check-your-answers.html
app/views/enforcement/v1/grounds/groundG-text.html

Showing data on Check your answers when nothing is entered and no skip links are clicked.

Showing data when none is entered

---

app/views/index.html

Enforcement 'Ready for UR' status on the index

Update to index status for enforcement journey, Ready for UR

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/check-your-answers.html
app/views/enforcement/v1/grounds/fees.html
app/views/enforcement/v1/grounds/groundA.html

We ask the question about fees if a person selects Ground A for their enforcement appeal.

Fees for Ground A

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/grounds/fees-exempt.html

Addition of fees exempt question.
If you selected Ground A and said you did not pay a fee, we ask if you are exempt.

Fees question

---

app/views/enforcement/v1/grounds/fees-exempt.html
app/views/enforcement/v1/grounds/fees.html

Changes to the titles for fees questions.

Updated content for fees

---

app/routes/enforcement/v1.js
app/views/enforcement/v1/grounds/application-decision.html
app/views/enforcement/v1/grounds/fees-exempt.html
app/views/enforcement/v1/grounds/groundA.html

The fees question moves to after the application

Fees question moved to after application question

---

app/routes/enforcement/v1.js

Fix so that everyone is asked about other appeals.

Ask everyone about other appeals

---

app/views/before-you-start/v11/check-answers.html

Making the deadline use the effective date for enforcement notices.

Fix to Before you start deadline

---

app/routes/enforcement/v2.js
app/views/enforcement/v2/grounds/grounds.html

Fixing the connection to routes from Grounds

Fix for v2 grounds

---

app/routes/enforcement/v2.js
app/views/enforcement/v2/grounds/groundA.html
app/views/enforcement/v2/grounds/groundB.html
app/views/enforcement/v2/grounds/groundC.html
app/views/enforcement/v2/grounds/groundD.html
app/views/enforcement/v2/grounds/groundE.html
app/views/enforcement/v2/grounds/groundF.html
app/views/enforcement/v2/grounds/groundG.html

Reverting grounds questions back to what we had in v1, leading with text input.

Updates to ground reason questions

---

app/routes/enforcement/v2.js
app/views/enforcement/v2/grounds/fees-exempt.html
app/views/enforcement/v2/grounds/fees.html
app/views/enforcement/v2/upload/plans-or-drawings.html

Enforcement v2 updates. Swapping the order of the enforcement notice and the plans question for uploads. Small content change for the fee questions.

Swapping plans and enf notice, fees content tweak

---

app/views/enforcement/v2/check-your-answers.html

Additional documents on check your answers table if people have said they have additional documents.

Enforcement, additional documents on check answers

---

app/routes/before-you-start/v11.js
app/routes/enforcement/v2.js
app/views/before-you-start/v11/appeal-intent.html
app/views/before-you-start/v11/check-answers.html
app/views/before-you-start/v11/date-of-intent.html
app/views/enforcement/v2/grounds/application-date.html
app/views/enforcement/v2/grounds/application-decision-date.html
app/views/enforcement/v2/grounds/groundB.html

Pulling conditionally revealled fieldsets out of radio options.

Fixing conditionally revealled content

---

app/views/enforcement/v2/grounds/fees.html

Fixing the thing I broke with the last change.

Fix to fees question

---

app/views/index.html

Adding links to the index for Listed buildings appeal version 16 (first and last name).

Listed building in index

---

app/views/before-you-start/v11/check-answers.html
app/views/before-you-start/v11/notice-type.html

Enforcement content update

---

app/views/enforcement/v3/check-your-answers.html
app/views/enforcement/v3/contact-details/add-person.html

Enforcement added person first and last name

---

app/views/enforcement/v3/check-your-answers.html

Removing a h2 in check answers.

Check answers clean up

---

app/views/appellant-submission/v16/before-you-start/planning-department.html
app/views/layouts/appellant-submission/v16.html

Fix to LPD version number using layout.

Fix to listed building LPD question

---

app/views/index.html

Making the index a bit more simple. Moving MVP section to accordion.

Index updates

---

app/views/before-you-start/v12/check-answers.html

Quick fix to BYS v12 check answers.

Fix Check answers for BYS

---

app/routes/before-you-start/v12.js
app/views/before-you-start/v12/appeal-intent.html
app/views/before-you-start/v12/date-of-intent.html
app/views/enforcement/v4/appeal-site/site-interest.html
app/views/enforcement/v4/before-you-continue.html
app/views/enforcement/v4/check-your-answers.html

Fixing a couple of edge pages that were flipping the prototype to older versions.

Routing updates to fix version hop

---

app/views/enforcement/v4/check-your-answers.html
app/views/enforcement/v4/upload/planning-obligation-status.html

Tidy up around data for planning obligation part of check answers.

Check answers tidy up updates

---

app/views/enforcement/v4/procedure/common-ground.html
app/views/enforcement/v4/procedure/inquiry-witnesses.html

Adding in upload statement of common of you select an inquiry.

Addition of statement of common ground

---

app/routes/enforcement/v4.js
app/views/enforcement/v4/check-your-answers.html
app/views/enforcement/v4/grounds/facts-format.html
app/views/enforcement/v4/grounds/groundA.html
app/views/enforcement/v4/grounds/groundB.html
app/views/enforcement/v4/grounds/groundC.html
app/views/enforcement/v4/grounds/groundD.html
app/views/enforcement/v4/grounds/groundE.html
app/views/enforcement/v4/grounds/groundF.html
app/views/enforcement/v4/grounds/groundG.html
app/views/enforcement/v4/grounds/grounds.html
app/views/enforcement/v4/grounds/upload-facts.html

Asking how people want to give us their reasons and facts. Playing back the content or filenames for the reasons on the check answers screen.

Format for reasons and facts and playback on check answers

---

app/views/enforcement/v4/check-your-answers.html

Enforcement, default reason if none are added.

Default value if no reasons are added

---

app/views/enforcement/v4/grounds/facts-format.html

Content update for one of the new questions around the format for your facts and reasons.

Content update for facts and reasons format

---

app/views/enforcement/v4/named-on-notice/added-names.html
app/views/enforcement/v4/named-on-notice/confirm-remove.html

The screen for when a name is removed.

Enforcement confirm remove name

---

app/views/enforcement/v4/named-on-notice/added-names.html
app/views/enforcement/v4/named-on-notice/confirm-remove.html

Small tweaks to the confirm remove screen content.

Enforcement small content change to confirm remove screen

---

app/views/enforcement-listed-building/v1/_routes.js
app/views/enforcement-listed-building/v1/check-your-answers.html
app/views/enforcement-listed-building/v1/grounds/application-decision-date.html
app/views/enforcement-listed-building/v1/grounds/application-decision.html
app/views/enforcement-listed-building/v1/grounds/application.html
app/views/enforcement-listed-building/v1/grounds/groundA.html
app/views/enforcement-listed-building/v1/grounds/groundB.html
app/views/enforcement-listed-building/v1/grounds/groundC.html
app/views/enforcement-listed-building/v1/grounds/groundD.html
app/views/enforcement-listed-building/v1/grounds/groundE.html
app/views/enforcement-listed-building/v1/grounds/groundF.html
app/views/enforcement-listed-building/v1/grounds/groundG.html
app/views/enforcement-listed-building/v1/listed-building/grade.html
app/views/enforcement-listed-building/v1/listed-building/grant-made.html
app/views/enforcement-listed-building/v1/listed-building/listed-date.html
app/views/enforcement-listed-building/v1/procedure/common-ground.html
app/views/enforcement-listed-building/v1/procedure/hearing.html
app/views/enforcement-listed-building/v1/task-list.html
app/views/index.html

Switching the version system / routes to the newer system, fixing routes.
Return of the enforcement statement link.

Listed building enforcement appeal journey, first cut

---

app/views/enforcement-listed-building/v1/_routes.js

Smol fix to the skip code to show an empty task list.

Skip code fix

---

app/views/enforcement-listed-building/v1/_routes.js

No change to what is shown, code is commented out in the routes.js for LBE.

Experimenting with the route for LBE

---

app/views/enforcement/v6/save-and-return/confirm-email.html
app/views/enforcement/v6/save-and-return/confirmation-email.html
app/views/enforcement/v6/save-and-return/email-confirmed.html
app/views/enforcement/v6/save-and-return/inbox-1.html
app/views/enforcement/v6/save-and-return/what-is-your-email.html
app/views/index.html

Adding Save and return screens for UR.

S&R added to enforcement appeal journey for UR

---

app/views/before-you-start/v12/check-answers.html
app/views/enforcement-statement/v1/appeal-submitted-email.html
app/views/enforcement/v6/confirmation.html

Linking up enforcement appeal journey and appeal started letter

---

app/routes/before-you-start/v12.js
app/views/before-you-start/v12/check-answers.html
app/views/before-you-start/v12/enforcement-effective-date.html

Fix to the intent date and showing this on Check answers (was working, somehow got broke)

Enforcement journey fix to enforcement effective date and intent

---

app/views/before-you-start/v12/index.html
app/views/index.html

Index update to BYS section

---

app/views/index.html

Update to index with Jira for S&R for enforcement updates

---

app/views/enforcement-statement/v1/appeal-started-email.html

Dropping in data from the appeal and dynamic dates.

Making the enforcement start letter more realistic

---

app/views/enforcement/v6/confirmation.html
app/views/index.html

Adding enforcement appeal journey data and dynamic dates.

Making the enforcement appeal start email more realistic

---

app/views/enforcement-statement/v1/update/index.html
app/views/enforcement/v6/grounds/reasons-alt-full.html
app/views/enforcement/v6/grounds/reasons-alt.html
app/views/index.html

This is a version of enforcement 'reasons' that adds more structure to the reasons. The idea here is to support appellants and influence behaviour of agents to the data instead of documents.

Enforcement appeal, more structure

---

app/views/enforcement/v6/appeal-site/site-visibility.html

Adding more help around the site visibility question.

Enforcement site visibility text

---

app/assets/sass/pins/tables.scss
app/views/enforcement/v7/_routes.js
app/views/enforcement/v7/check-your-answers.html
app/views/enforcement/v7/procedure/procedure.html

Changes to table to include a table divider for grounds section of Check answers, also showing what a table might look like with no last table row border.

Enforcement table changes test

---

app/views/enforcement/v7/_routes.js

Fix to the 'skipping' function to get to a completed Check answers

Tiny fix from the last push

---

app/views/accessibility-statement/index.html
app/views/accessibility-statement/v1/_routes.js
app/views/accessibility-statement/v1/question.html

First pass of the accessibility statement (footer content) template

Accessibility statement template

---

app/views/index.html

Adding footer pages (accessibility statement) to index

Footer pages added to index

---

app/views/enforcement-listed-building/v1/appeal-site/site-visibility.html
app/views/enforcement-listed-building/v1/grounds/groundA.html
app/views/enforcement-listed-building/v1/grounds/groundB.html
app/views/enforcement-listed-building/v1/grounds/groundC.html
app/views/enforcement-listed-building/v1/grounds/groundD.html
app/views/enforcement-listed-building/v1/grounds/groundE.html
app/views/enforcement-listed-building/v1/grounds/grounds.html

LBE ground reason updates

---

app/views/enforcement-listed-building/v1/_routes.js
app/views/enforcement-listed-building/v1/appeal-site/site-visibility.html
app/views/enforcement-listed-building/v1/grounds/application-date.html
app/views/enforcement-listed-building/v1/grounds/supporting-check.html
app/views/enforcement-listed-building/v1/grounds/supporting-upload.html
app/views/enforcement/v7/_routes.js
app/views/enforcement/v7/appeal-site/site-visibility.html
app/views/enforcement/v7/grounds/application-date.html
app/views/includes/enforcement/site-visibility.html

Updates to LBE to bring it inline with enforcements.

Enforcement appeal alignments

---

app/views/enforcement-listed-building/v1/_routes.js
app/views/enforcement-listed-building/v1/grounds/groundC.html
app/views/enforcement-listed-building/v1/grounds/groundD.html
app/views/enforcement-listed-building/v1/grounds/groundE.html
app/views/enforcement-listed-building/v1/grounds/groundF.html
app/views/enforcement-listed-building/v1/grounds/groundG.html
app/views/enforcement-listed-building/v1/grounds/groundH.html
app/views/enforcement-listed-building/v1/grounds/groundI.html
app/views/enforcement-listed-building/v1/grounds/groundJ.html
app/views/enforcement-listed-building/v1/grounds/groundK.html
app/views/enforcement-listed-building/v1/grounds/grounds.html
app/views/enforcement-listed-building/v1/listed-building/grant-made.html

Updating the grounds content (grounds and reasons), adding in ground screens and logic.

LB enforcement appeals, content updates

---

app/views/enforcement-listed-building/v1/_routes.js
app/views/enforcement-listed-building/v1/appeal-site/grid-address.html
app/views/enforcement-listed-building/v1/appeal-site/health-and-safety-issues.html
app/views/enforcement-listed-building/v1/appeal-site/postcode-address.html
app/views/enforcement-listed-building/v1/appeal-site/site-occupation.html
app/views/enforcement-listed-building/v1/appeal-site/site-visibility.html
app/views/enforcement-listed-building/v1/appeal-site/your-interest.html

Fix to appeal site routing so that other appeals are asked about

LB enforcement appeal sites fixes

---

app/views/enforcement-listed-building/v1/confirmation.html

Tiny change to the confirmation page for the LB enforcement journey

---

app/views/enforcement/v8/contact-details/added-names.html

Small fix to playback of company/person names.

Small change to added names

---

app/views/enforcement-listed-building/v1/_routes.js
app/views/enforcement-listed-building/v1/contact-details/added-names.html
app/views/enforcement-listed-building/v1/contact-details/appellant-name.html
app/views/enforcement-listed-building/v1/contact-details/application-check.html
app/views/enforcement-listed-building/v1/contact-details/company-name.html
app/views/enforcement-listed-building/v1/contact-details/index.html
app/views/enforcement-listed-building/v1/task-list.html
app/views/enforcement/v8/_routes.js

Update to listed building enforcement appealss to include our new version of the contact details task.

Update to contacts and company names to listed building enforcements

---

app/views/before-you-start/v12/index.html

Fixing the link for v12 for Before you start

Before you start fix

---

app/views/final-comments/v2/_routes.js
app/views/final-comments/v2/comment.html
app/views/final-comments/v2/confirmation.html
app/views/final-comments/v2/documents-email.html
app/views/final-comments/v2/input-code.html
app/views/final-comments/v2/supporting-check.html
app/views/final-comments/v2/supporting-upload.html
app/views/includes/button-and-save-link.html
app/views/index.html

First draft of the final comments journey MVP

Final comments start

---

app/views/enforcement-listed-building/v1/_routes.js
app/views/final-comments/v2/documents-email.html
app/views/final-comments/v2/supporting-check.html

Adding a back link to the final comments journey.
Also noticed that listed building enforcement contact section was taking the user to the enforcement journey.

Adding a back link and fixing some LBE links

---

app/views/index.html

Tiny change to index

---

app/views/enforcement-listed-building/v1/contact-details/appellant-name.html
app/views/enforcement/v8/contact-details/appellant-name.html
app/views/final-comments/v2/_routes.js
app/views/final-comments/v2/documents-email.html

Small update to final comments and a tiny content change for enforcement.

Updates to final comments + content tweak for enforcement

---

app/views/final-comments/v2/_routes.js
app/views/final-comments/v2/input-code.html
app/views/final-comments/v2/no-final-comments.html
app/views/final-comments/v2/supporting-check.html
app/views/final-comments/v2/supporting-upload.html
app/views/includes/button.html
app/views/index.html
app/views/service-unavailable/v1/index.html

Final comment updates

---

app/views/final-comments/v2/_routes.js

Small fix to Final comments routing

---

app/views/index.html

Extra links for final comments on the index.

More index links for the final comments journey

---

app/views/final-comments/v2/_routes.js
app/views/final-comments/v2/final-comments.html

Final comments minor changes

---

app/views/final-comments/v2/_routes.js
app/views/final-comments/v2/case-officer/appeal-link.html
app/views/final-comments/v2/case-officer/appeal-not-found.html
app/views/final-comments/v2/case-officer/appeal-search.html
app/views/final-comments/v2/case-officer/appeal.html
app/views/final-comments/v2/case-officer/before-you-continue.html
app/views/final-comments/v2/case-officer/check-your-answers.html

Case officer journey to make an appeal beta service link

Case officer makes a beta link

---

app/views/final-comments/v2/case-officer/appeal-link.html
app/views/final-comments/v2/case-officer/appeal-not-found.html
app/views/final-comments/v2/case-officer/appeal-search.html
app/views/final-comments/v2/case-officer/appeal.html

Updates to the appeal table data and a new link for the actual code link

Small changes to Case Officer code journey

---

app/views/final-comments/v2/case-officer/appeal-link.html
app/views/final-comments/v2/case-officer/appeal-not-found.html
app/views/final-comments/v2/case-officer/appeal-search.html
app/views/final-comments/v2/case-officer/appeal.html
app/views/final-comments/v2/case-officer/before-you-continue.html
app/views/final-comments/v2/case-officer/check-your-answers.html

Small changes to Case officer journey to make a Beta service link. Small content changes.

Additions to the case officer journey

---

app/views/final-comments/v2/case-officer/appeal-link.html
app/views/layout-lpa.html
app/views/lpa/v1/_routes.js
app/views/lpa/v1/access-given.html
app/views/lpa/v1/access.html
app/views/lpa/v1/appeals.html
app/views/lpa/v1/check-email.html
app/views/lpa/v1/confirm-remove.html
app/views/lpa/v1/enter-code.html
app/views/lpa/v1/give-access.html
app/views/lpa/v1/question.html
app/views/lpa/v1/request-for-information.html

First pass of invite to account, appeals, managing shared access.

Lpa accounts start

---

app/views/lpa/v1/appeals.html

Dropping in a couple of links to questionnaire versions (normal and non-determination).

Appeal links to Questionnaire versions

---

app/views/lpa/v1/_routes.js
app/views/lpa/v1/access.html
app/views/lpa/v1/appeals.html
app/views/lpa/v1/email.html
app/views/lpa/v1/start.html
app/views/lpa/v1/use-code.html

A service start page, entering your email address, your email address shows in access table

LPA service start page entry

---

app/views/lpa/v1/access.html
app/views/lpa/v1/appeals-later.html
app/views/lpa/v1/appeals.html
app/views/lpa/v1/no-appeals.html

Moving the links to the footer.

Prototype only links

---

app/views/lpa/v1/_routes.js
app/views/lpa/v1/access.html
app/views/lpa/v1/check-email.html
app/views/lpa/v1/confirm-remove.html
app/views/lpa/v1/give-access.html

Chris did some updates including getting the access list addition and removal working so that mutliple users can be added. In that update there were some other changes, some of this has been regressed to match the rest of the service at this time.

Lpa service

---

app/views/lpa/v1/no-appeals.html

Noticed that one page had the wrong service header, fixed here.

No-appeals has the wrong header

---

app/views/index.html
app/views/lpa/v2/_layout.html
app/views/lpa/v2/_routes.js
app/views/lpa/v2/access.html
app/views/lpa/v2/appeals.html
app/views/lpa/v2/check-email.html
app/views/lpa/v2/confirm-remove.html
app/views/lpa/v2/email.html
app/views/lpa/v2/enter-code.html
app/views/lpa/v2/give-access.html
app/views/lpa/v2/manage-appeals.html
app/views/lpa/v2/no-appeals.html
app/views/lpa/v2/question.html
app/views/lpa/v2/request-code.html
app/views/lpa/v2/request-for-information.html
app/views/lpa/v2/service-invite.html
app/views/lpa/v2/start.html

Update to appeals list showing tasks for multiple appeals.
1. Appeals are ordered so that appeals that need action are shown first
2. Moved some content on the 'no appeals' screen to a notification banner

Lpa service version 2 start

---

app/assets/sass/pins/tables.scss
app/views/lpa/v2/appeals.html

Small change to one of the table headers.

lpa account table update

---

app/views/index.html

Test change to check new pipeline.

Test change

---

app/views/manage/appeals/v2/index.html

Fixing one of the appeal links.

Fix to lpa statement link

---

app/views/manage/appeals/v2/index.html

Changing appeals list table headings, content update.

Small content change to appeals table headers

---

app/views/manage/appeals/index.html
app/views/manage/appeals/v2/index.html
app/views/manage/final-comments/v1/_routes.js
app/views/manage/final-comments/v1/add-comments.html
app/views/manage/final-comments/v1/check-your-answers.html
app/views/manage/final-comments/v1/confirmation.html
app/views/manage/final-comments/v1/documents-check.html
app/views/manage/final-comments/v1/documents-upload.html
app/views/manage/questionnaire/v11/_routes.js
app/views/manage/questionnaire/v11/confirmation.html
app/views/manage/questionnaire/v11/task-list.html
app/views/manage/statement/v1/_routes.js
app/views/manage/statement/v1/check-your-answers.html
app/views/manage/statement/v1/confirmation.html
app/views/manage/statement/v1/documents-check.html
app/views/manage/statement/v1/documents-upload.html
app/views/manage/statement/v1/enter-statement.html

Alignment across Questionnaire, Appeal statement and FInal comments.
- updated Beta phase banner (not added to questionnaire)
- added meta data to the front screen of each (statement / final comments)
- added ‘Back to appeals’ back link

Updates to LPA account

---

app/assets/sass/application.scss
app/assets/sass/pins/pins_tables.scss
app/views/interested/comment/v5/_routes.js
app/views/interested/comment/v6/_routes.js
app/views/interested/comment/v6/check-your-answers.html
app/views/interested/find-appeal/v5/_routes.js
app/views/interested/find-appeal/v5/appeal-details.html
app/views/interested/find-appeal/v5/appeal-search-address.html
app/views/interested/find-appeal/v5/appeal-search-grid-reference.html
app/views/interested/find-appeal/v5/appeal-search-number.html
app/views/interested/find-appeal/v5/closed-appeals.html
app/views/interested/find-appeal/v5/open-appeals.html

Updates to interested parties can comment.
Addition of grid search, tab UI to appeal details, logic for showing an extra tab when appeals are decided.

Interested parties can comment updates, grid search, tab view

---

app/views/_includes/appeal-content/full-appeal-decision-allowed.html
app/views/_includes/appeal-content/full-appeal-details.html
app/views/_includes/appeal-content/full-appeal-summary.html
app/views/index.html
app/views/interested/find-appeal/v5/appeal-details.html
app/views/interested/find-appeal/v5/appeal-search-address.html
app/views/interested/find-appeal/v5/guidance.html

Appeal summary + details data and documents in the 2nd tab.
Decided appeals showing decision data and documents.

Interested parties update, appeal documents

---

README.md
app/views/_includes/appeal-content/full-appeal-details.html
app/views/_layouts/layout-email.html
app/views/index.html
app/views/interested/comment/index.html
app/views/interested/comment/v5/appeal-comment-email.html
app/views/interested/comment/v5/appeal-comment-name.html
app/views/interested/comment/v5/appeal-details.html
app/views/interested/comment/v5/check-answers.html
app/views/interested/comment/v5/comment-received.html
app/views/interested/comment/v5/comment-upload-list.html
app/views/interested/comment/v5/comment-upload.html
app/views/interested/comment/v5/guidance.html
app/views/interested/comment/v6/_routes.js
app/views/interested/comment/v6/add-comments.html
app/views/interested/find-appeal/index.html
app/views/interested/find-appeal/v5/_routes.js
app/views/interested/find-appeal/v5/appeal-details.html
app/views/interested/find-appeal/v5/appeal-notice-email-full.html
app/views/interested/find-appeal/v5/appeal-notice-email-householder.html
app/views/interested/find-appeal/v5/appeal-search-address.html
app/views/interested/find-appeal/v5/appeal-search-no-results.html
app/views/interested/find-appeal/v5/appeal-search-number.html
app/views/interested/find-appeal/v5/closed-appeals.html
app/views/interested/find-appeal/v5/guidance.html
app/views/interested/find-appeal/v5/open-appeals.html

LPA > Interested Party notification email content + some other updates for interested parties.

Interested party updates and email notification content

---

app/views/interested/comment/v6/confirmation.html
app/views/interested/comment/v6/documents-check.html
app/views/interested/comment/v6/your-email.html
app/views/interested/comment/v6/your-name.html
app/views/interested/find-appeal/v5/appeal-decision.html
app/views/interested/find-appeal/v5/appeal-details.html
app/views/interested/find-appeal/v5/appeal-notice-email-full.html
app/views/interested/find-appeal/v5/appeal-notice-email-householder.html
app/views/interested/find-appeal/v5/guidance.html
app/views/interested/find-appeal/v5/open-appeals.html
app/views/manage/access/v1/start.html

Updates to the comment journey:
- a url in the email now
- comments > comment (we might need to undo this)
- tabs only for decided appeals (still needs consideration)

Interested parties can comment, changes

---

app/views/_includes/appeal-content/appeal-lpa-metadata.html
app/views/interested/comment/v7/add-comments.html
app/views/interested/comment/v7/check-your-answers.html
app/views/interested/comment/v7/your-email.html
app/views/interested/comment/v7/your-name.html
app/views/interested/find-appeal/v6/appeal-details.html
app/views/interested/find-appeal/v6/appeal-notice-email-full.html
app/views/manage/appeals/index.html
app/views/manage/appeals/v3/_routes.js
app/views/manage/appeals/v3/index.html
app/views/manage/notify/v1/_routes.js
app/views/manage/notify/v1/send-email.html
app/views/manage/notify/v1/send-new.html

Work in progress on the LPA feature to send notices to interested parties.

LPA can send notices to interested parties (a start)

---

app/views/index.html
app/views/interested/find-appeal/v6/appeal-notice-email-full.html
app/views/manage/appeals/v3/index.html
app/views/manage/emails/v1/appeal-valid.html

Small updates to interested party comms and an update to the index presentation.

Small updates to IP work and change to index

---

app/views/index.html
app/views/manage/notify/index.html

Small updates to the links for LPAs.

Small updates to index

---

app/views/index.html
app/views/interested/index.html

Small updates to the index and the LPA dashboard.

Updates to LPA work and the index

---

app/views/manage/appeals/v3/index.html
app/views/manage/notify/index.html
app/views/manage/notify/v1/_routes.js
app/views/manage/notify/v1/check-list.html
app/views/manage/notify/v1/send-new.html

Updates for the IP notices, print a notice and combined check answers for the list of recipients.

LPA IP notice print option, combined check recipients list
